stock_management/dashboard/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'dashboard'


urlpatterns = [
    path('',views.HomePage.as_view(),name = 'homepage'),
    url(r'^items$',views.ItemListView.as_view(),name='item_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^item/(?P<pk>\d+)$', views.ItemDetailView.as_view(), name='item_detail'),
    url(r'^item/new/$', views.CreateItemView.as_view(), name='item_new'),
    url(r'^item/(?P<pk>\d+)/edit/$', views.ItemUpdateView.as_view(), name='item_edit'),
    url(r'^item/(?P<pk>\d+)/remove/$', views.ItemDeleteView.as_view(), name='item_remove'),
    url(r"login/$", auth_views.LoginView.as_view(template_name="dashboard/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    path('results/',views.search, name='search'),
    path('item/sell/',views.SellItem.as_view(),name = 'item_sell'),
    path('item/add/',views.AddItem.as_view(),name = 'item_add'),
    path('item/low/',views.LowItem.as_view(),name = 'item_low')

    # url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
]

stock_management/stock_management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf.urls import url

app_name = 'stock_management'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    
]

stock_management/dashboard/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib import auth
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib.auth.models import User



class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

MyUser=get_user_model()
class Item(models.Model):
    user = models.ForeignKey(auth.models.User, on_delete=models.CASCADE,default=1)
    name = models.CharField(max_length=200)
    brand = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    price = models.IntegerField()
    quantity = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    total_price= models.IntegerField(default=0)



    def publish(self):
        self.user=self.request.get('User')
        self.save()


    def get_absolute_url(self):
        return reverse("item_detail",kwargs={'pk':self.pk})


    def __str__(self):
        return self.name

stock_management/dashboard/forms.py
from django import forms

from .models import Item
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm



class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"


class AddItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ('user','name','brand','category','price', 'quantity','total_price')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'textinputclass'}),
            'brand': forms.TextInput(attrs={'class': 'textinputclass'}),
            'price': forms.TextInput(attrs={'class': 'textinputclass'}),
            'quantity': forms.TextInput(attrs={'class': 'textinputclass'}),
        }

stock_management/dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from dashboard.models import Item
from django.utils import timezone
from dashboard.forms import AddItemForm
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout
from .forms import UserCreateForm
from django.db.models import Q
from django.views.generic.edit import ModelFormMixin


class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy("dashboard:login")
    template_name = "dashboard/signup.html"



class HomePage(LoginRequiredMixin,TemplateView):
    login_url = '/login/'
    template_name = 'dashboard/mainpage.html'
    model = Item
    def get_queryset(self):
        return Item.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')

class AboutView(TemplateView):
    template_name = 'about.html'



class ItemListView(LoginRequiredMixin,ListView):
     login_url = '/login/'
     redirect_field_name = 'dashboard/item_list.html'
     model = Item
     def get_queryset(self):
         return Item.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')



     def get_queryset(self):
         return Item.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')



class ItemDetailView(LoginRequiredMixin,DetailView):
    login_url='/login/'
    redirect_field_name = 'dashboard/item_detail.html'
    model = Item


class CreateItemView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'dashboard/item_new.html'

    form_class = AddItemForm

    model = Item
    success_url=reverse_lazy('dashboard:item_list')


class ItemUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'dashboard/item_list.html'
    success_url = reverse_lazy('dashboard:item_list')

    form_class = AddItemForm

    model = Item

class ItemDeleteView(LoginRequiredMixin,DeleteView):
    model = Item
    success_url = reverse_lazy('dashboard:item_list')

class SellItem(LoginRequiredMixin,TemplateView):
    login_url = '/login/'
    redirect_field_name = 'dashboard/item_sell.html'
    template_name='dashboard/item_sell.html'

    # def post(self,request,*args,**kwargs):
    #     print(request.POST.get("name"))

class AddItem(LoginRequiredMixin,TemplateView):
    login_url = '/login/'
    redirect_field_name = 'dashboard/item_add.html'
    template_name='dashboard/item_add.html'


class LowItem(LoginRequiredMixin,TemplateView):
    login_url = '/login/'
    redirect_field_name = 'dashboard/item_low.html'
    template_name='dashboard/item_low.html'


def search(request):

    items = Item.objects.all()
    search_term = ''

    search_term = request.GET['search']
    items = items.filter(name__icontains=search_term)
    context = {"items": items, "search_term":search_term}
    return render(request,'dashboard/item_search.html', context)

stock_management/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Stock Management</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <style>
  .cap {
     text-transform: capitalize;
 }

  .fakeimg {
      height: 200px;
      background: #aaa;
  }
  .fa {
  padding: 20px;
  font-size: 30px;
  width: 50px;
  text-align: center;
  text-decoration: none;
  margin: 5px 2px;

  .fa:hover {
    opacity: 0.7;
    .fa-android {
    background: #a4c639;
    color:white ;



  </style>
</head>
<body>

<div class="jumbotron text-center" style="margin-bottom:0; background-image:url(http://3.bp.blogspot.com/-P63GODoAMvk/VyW-IUiicWI/AAAAAAAAy4Y/6t7zXRaflpcQSZK0Aw4MWbBNMqV_FeqcACHM/s1600/black-background-wood-hd-desktop-wallpaper-widescreen-high.jpg); margin-bottom: 0px;
background-position: 0% 25%;
  background-size: cover;
  background-repeat: no-repeat;
  color: white;" >
  <h1 styale="font-size : 200%;">STOCK MANAGEMENT</h1>
  <p>We are an Online Inventory Management solution provider...!</p>
</div>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="{% url 'dashboard:homepage' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      </ul>

      <ul class=" navbar-nav navbar-right">

        {% if user.is_authenticated %}
        <li>
        <a class="nav-link" href="{%url 'dashboard:logout' %}">Logout</a>
        <li>
        <li>
        <a class="nav-link" href=""></a>
        <li>
        <li>
        <a class="nav-link" href=""></a>
        <li>
        <form class="form-inline my-2 my-lg-0" action="{% url 'dashboard:search' %}">
          <input class="form-control mr-sm-2" type="search" name='search' placeholder="Search" aria-label="Search" value={{ request.GET.search}}>
          <button class="btn btn-outline-success my-2 my-sm-0" type="search">Search</button>
        </form>
        <li>
        <li>
        {% else %}
        <a class="nav-link" href="{%url 'dashboard:signup' %}">Create Account</a>
        {% endif %}

    </ul>

  </div>
</nav>




{% block content %}


{% endblock content %}

<div class="jumbotron text-center" style="margin-bottom:0; align:center;">
<div class="container text-center">

  <a href="#" class="fa fa-android"></a>
<p>Email:  stockmanagement@gmail.com</p>
<p>Toll free no.: 1800-180-340</p>
<p>Name: Bhavya Paliwal
</div>
</div>

</body>
</html>

stock_management/templates/dashboard/homepage.html
{% extends "base.html "%}

{% block content %}
<div class="jumbotron text-center">
  <div class="container">

  <h1>Sign up here </h1>
  <h2>Stay managed with us</h2>
    <form>
      <div class="form-group">
        <label for="name">Full Name</label>
        <input type="text" class="form-control" name="name" placeholder="Your Name">

      </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="btn-group">
<button type="submit" class="btn btn-primary">Submit</button>
</div>
</div>

</div>

</form>

</div>
 {% endblock %}

stock_management/templates/dashboard/item_add.html
{% extends 'base.html' %}

{% block content %}
<br><br>



<div class="centerstage jumbotron">

<form class="form" action="{% url 'dashboard:homepage'%}" method="post">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Name of item">
  <input type="number" name="quantity" placeholder="No. of item">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add</button>
</form>





</div>

{% endblock %}

stock_management/templates/dashboard/item_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="form-group" style="text-align:center;">


<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ item.name }}"?</p>
    <input type="submit" value="Confirm">
</form>
</div>
</div>


{% endblock content %}

stock_management/templates/dashboard/item_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">

  <div class="container" style="text-align: center;">
    <table class="table">
      <thead class="thead-dark">

    <tr>



      <th>Name</th>
      <th>Brand</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th>Entry Date</th>
      <th>User</th>
    </tr>
      </thead>
    <tr>
      <td>{{item.name }}</td>
      <td>{{item.brand}}</td>
      <td>{{item.price}}</td>
      <td>{{item.quantity}}</td>
      <td>{{item.total_price}}</td>
      <td>{{item.created_date}}</td>
      <td>{{item.user}}</td>
    </tr>
    </table>

  </div>
</div>
{% endblock content %}

stock_management/templates/dashboard/item_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Item</h1>


    <form method="POST" class="form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default form-group">Save</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

stock_management/templates/dashboard/item_list.html
{% extends 'base.html' %}

{% block content %}
<br><br>



<div class="centerstage jumbotron">
  <table class="table">
    <thead class="thead-dark">


    <tr>

      <th>Name</th>
      <th>Brand Name</th>
      <th>Category</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th></th>
      <th></th>
    </tr>
</thead>


{% for item in item_list %}
<!-- {% if item.user.pk == user.pk %} -->

<tr>


        <div class="post">
          <div class="container">
            <td><h1><a class="cap" href="{% url 'dashboard:item_detail' pk=item.pk %}">{{ item.name }}</a></h1></td>
            <td><h1 class="cap">{{ item.brand }}</h1></td>
            <td><h1>{{ item.category }}</h1></td>
            <td><h1>{{ item.price }}</h1></td>
            <td><h1>{{ item.quantity }}</h1></td>
            <td><h1>{{ item.total_price }}</h1></td>
            <td><a class="btn btn-primary" href="{% url 'dashboard:item_edit' pk=item.pk %}">Edit</span></a></td>
            <td><a class="btn btn-danger" href="{% url 'dashboard:item_remove' pk=item.pk %}">Remove</span></a></td>


          </tr>
          </div>
    <!-- {%else%}

    {%endif%} -->
    {% endfor %}
</div>
</table>

</div>
<br><br>

<form method="get" action="{% url 'dashboard:item_new' %}" class="form-group">
<button type="submit" class="btn btn-success" href="" style="text-align: center;
    border: 3px solid green;">Add Item</button>
</div>

{% endblock %}

stock_management/templates/dashboard/item_low.html
{% extends 'base.html' %}

{% block content %}
<br><br>



<div class="centerstage jumbotron">
  <table class="table">
    <thead class="thead-dark">


    <tr>

      <th>Name</th>
      <th>Brand Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th></th>
      <th></th>
    </tr>
</thead>


{% for item in item_list %}
{% if item.quantity <= 10 %}

<tr>


        <div class="post">
          <div class="container">
            <td><h1><a class="cap" href="{% url 'dashboard:item_detail' pk=item.pk %}">{{ item.name }}</a></h1></td>
            <td><h1 class="cap">{{ item.brand }}</h1></td>
            <td><h1>{{ item.price }}</h1></td>
            <td><h1>{{ item.quantity }}</h1></td>
            <td><h1>{{ item.total_price }}</h1></td>
            <td><a class="btn btn-primary" href="{% url 'dashboard:item_edit' pk=item.pk %}">Edit</span></a></td>
            <td><a class="btn btn-danger" href="{% url 'dashboard:item_remove' pk=item.pk %}">Remove</span></a></td>


          </tr>
          </div>
    {%else%}

    {%endif%}
    {% endfor %}
</div>
</table>

</div>
<br><br>

<form method="get" action="{% url 'dashboard:item_new' %}" class="form-group">
<button type="submit" class="btn btn-success" href="" style="text-align: center;
    border: 3px solid green;">Add Item</button>
</div>

{% endblock %}

stock_management/templates/dashboard/item_new.html
{% extends 'base.html' %}

{% block content %}
{% load bootstrap3 %}
<div class="container text-center">


    <h1>New Item</h1>


    <div style="margin:auto;">

    <form method="POST" class="form" >
    {% csrf_token %}
    {{ bootstrap_form form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>

  </div>

    <script>var editor = new MediumEditor('.editable');</script>

    </div>
{% endblock %}

stock_management/templates/dashboard/item_search.html
{% extends 'base.html' %}

{% block content %}
<br><br>




<div class="centerstage jumbotron">
  <table class="table">
    <thead class="thead-dark">


    <tr>

      <th>Name</th>
      <th>Brand Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total Price</th>
      <th></th>
      <th></th>
    </tr>
</thead>

{% for item in items %}
<tr>


        <div class="post">
          <div class="container">
            <td><h1><a href="{% url 'dashboard:item_detail' pk=item.pk %}">{{ item.name }}</a></h1></td>
            <td><h1>{{ item.brand }}</h1></td>
            <td><h1>{{ item.price }}</h1></td>
            <td><h1>{{ item.quantity }}</h1></td>
            <td><h1>{{ item.total_price }}</h1></td>
            <td><a class="btn btn-primary" href="{% url 'dashboard:item_edit' pk=item.pk %}">Edit</span></a></td>
            <td><a class="btn btn-danger" href="{% url 'dashboard:item_remove' pk=item.pk %}">Remove</span></a></td>


          </tr>
          </div>

    {% endfor %}
</div>
</table>

</div>
<br><br>

<form method="get" action="{% url 'dashboard:item_new' %}" class="form-group">
<button type="submit" class="btn btn-success" href="">Add Item</button>
</div>

{% endblock %}

stock_management/templates/dashboard/item_sell.html
{% extends 'base.html' %}

{% block content %}
<br><br>



<div class="centerstage jumbotron">

<form class="form" action="{% url 'dashboard:homepage'%}" method="post">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Name of item">
  <input type="number" name="quantity" placeholder="No. of item">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sell</button>
</form>





</div>

{% endblock %}

stock_management/templates/dashboard/login.html
{% extends 'base.html' %}


{% block content %}
  <div class="jumbotron">


    {% if form.errors %}
        <p>Your username and password didn't match.Please try again!</p>
    {% endif %}

    <form method="POST" >
    {% csrf_token %}
        {{form.as_p}}

        <input type="submit" class='btn btn-primary' value="Login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
  </div>
{% endblock %}

stock_management/templates/dashboard/mainpage.html
{% extends "base.html" %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:200px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }
  }
  </style>
</head>
<body>



<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <a href="" +*><img src="https://cdn.lynda.com/course/731733/731733-636709657836809274-16x9.jpg" alt="Image"></a>
        <div class="carousel-caption">
          <h3>Sell $</h3>
          <p>Money Money.</p>
        </div>
      </div>

      <div class="item">
        <img src="http://www.america-retail.com/static//2018/04/inventory.png" alt="Image">
        <div class="carousel-caption">
          <h3>More Sell $</h3>
          <p>Lorem ipsum...</p>
        </div>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

<div class="jumbotron">
  <div class="container text-center">
    <h3>What We Do</h3><br>
    <div class="row">
      <div class="col-sm-4" style="background-color:#ff9a9a;">

        <a href="{% url 'dashboard:item_list' %}">
          <h1>Manage Stock</h1>

        </a>

      </div>
      <div class="col">
        <div class="col-sm-4" style="background-color:	#fff9be;">

          <a href="{% url 'dashboard:item_sell' %}">
            <h1>Sell Item</h1>

          </a>

        </div>
        <div class="col">
          <div class="col-sm-4" style="background-color:#cdffbe;">

            <a href="{%url 'dashboard:item_add' %}">
              <h1>Add Stock</h1>

            </a>

          </div>
          <div class="col">
            <div class="col-sm-4" style="background-color:#b0fdff;">

              <a href="{% url 'dashboard:item_low' %}">
                <h1>Low Stock</h1>

              </a>

            </div>


    </div>

</div>
</div><br>


</body>
</html>


{% endblock content %}

stock_management/templates/dashboard/signup.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<br>


<div class="container">
    <h1>Sign Up</h1>
    <form method="POST" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
<br>

{% endblock content %}